#!/bin/sh


# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

if [ ! -d "/boot" ]; then
	mkdir /boot
fi

if [ ! -d "/boot" ]; then
	mkdir /boot
fi

mount /dev/mmcblk0p1 /boot
modetest -M vc4 -s 32@71:1440x1600 -v
